### ISSUE TITLE
This is an awesome project!

### ISSUE THREAD

**Issue by Sean-Der** [smf8/kenny#1]
Hey @smf8 

I am really excited to see this project. It will unlock a lot of new use cases if people can use a CLI application. In the future I might open a PR so users can join other SFUs (Jitsi, Janus, Mediasoup...) and maybe proprietary services even.

If there is anything I can do to help email me at anytime sean @ pion.ly or in [Slack](https://pion.ly/slack)

**Comment by smf8** [comment]
Hello dear Sean,

That would be awesome. I think it will be really great to have a fully functional yet detached from browser application.

Also, thank you for offering help, you and pion community have helped a lot. I'll surely ask.

**Comment by smf8** [comment]
Hello dear Sean,

That would be awesome. I think it will be really great to have a fully functional yet detached from browser application.

Also, thank you for offering help, you and pion community have helped a lot. I'll surely ask.
